import = [
    "~/.config/alacritty/themes/themes/flexoki-light.toml"
]

[env]
TERM = "screen-256color"

[font]
size = 20
offset = { x = 0, y = 10 }
glyph_offset = { x = 0, y = 8 }
normal      = { family = "Zed Mono", style = "Regular" }
bold        = { family = "Zed Mono", style = "Bold" }
italic      = { family = "Zed Mono", style = "Italic" }
bold_italic = { family = "Zed Mono", style = "Bold Italic" }

[window]
option_as_alt = "Both"
decorations = "none"
